apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-operator-ingress
  namespace: login
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: login-coraza-waf@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: admin.example.com
      http:
        paths:
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: login-operator
                port:
                  number: 80
