# 베이스 이미지 (풀버전)
FROM confluentinc/cp-kafka-connect:7.5.0

# unzip 설치를 위해 임시로 root 권한 획득
USER root

# apt 패키지 매니저 업데이트 및 unzip 설치
RUN apt-get update && \
    apt-get install -y --no-install-recommends unzip && \
    rm -rf /var/lib/apt/lists/* # 설치 후 캐시 삭제로 이미지 용량 최적화

# 필수 커넥터 미리 설치 (빌드 시점)
# S3(10.5.0)와 Azure(2.5.3) 버전을 명시하여 라이선스 충돌 방지
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-azure-blob-storage:2.5.3 && \
    confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.5.0

# 다시 기본 사용자로 돌아가기 (보안 유지)
USER appuser

# 실행 명령 (기본값 유지)
CMD ["/etc/confluent/docker/run"]