name: 'Azure Infrastructure Deploy'

on:
  workflow_dispatch:
    inputs:
      action:
        description: '실행할 작업을 선택하세요.' # apply: 생성 / destroy: 삭제
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy

env:
  # Azure에 로그인하기 위한 인증 정보
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # variables.tf로 밀어 넣을 비밀 정보
  TF_VAR_public_key: ${{ secrets.AZURE_PUBLIC_KEY }}
  TF_VAR_db_password: ${{ secrets.AZURE_DB_PASSWORD }}

jobs:
  terraform-azure:
    name: 'Terraform Azure'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/azure/terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform apply -auto-approve

    # Terraform Output을 Inventory 파일로 변환
    - name: Generate Ansible Inventory
      if: ${{ github.event.inputs.action == 'apply' }}
      run: |
        BROKER_IP=$(terraform output -raw broker_public_ip)
        CONSUMER_IP=$(terraform output -raw consumer_public_ip)
        VM_USER=$(terraform output -raw admin_username)
        
        # Terraform 폴더 안에 파일 생성 (Terraform이 준 IP 정보를 즉시 사용 위함)
        cat <<EOF > azure_hosts.ini
        [azure_broker]
        broker-vm ansible_host=${BROKER_IP}

        [azure_consumer]
        consumer-vm ansible_host=${CONSUMER_IP}

        [azure_vms:children]
        azure_broker
        azure_consumer

        [azure_vms:vars]
        ansible_user=${VM_USER}
        ansible_python_interpreter=/usr/bin/python3
        EOF

    # SSH 키 설정 (접속용)
    - name: Set up SSH Key
      if: ${{ github.event.inputs.action == 'apply' }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AZURE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa # 보안 강화

    # Ansible 실행
    - name: Run Ansible Playbook
      if: ${{ github.event.inputs.action == 'apply' }}
      run: |
        ansible-playbook -i azure_hosts.ini ../ansible/playbook.yml \
          -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"

    - name: Terraform Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform destroy -auto-approve